name: catsdogs_with_test

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - pip
  - openjdk=17

  # ML deps you already use
  - pytorch
  - torchvision
  - pillow
  - pyyaml

  # test runner
  - pytest

  # PyDeequ + Spark (pin to compatible versions)
  - pip:
      - pyspark==3.3.0
      - pydeequ==1.1.0
