paths:
  data_root: data/datav1
  train_data: null #Overridden dynamically in the code
  val_data: null   #Overridden dynamically in the code
  test_data: null  #Overridden dynamically in the code
dataset:
  image_size: 224

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  weight_decay: 0.0

misc:
  seed: 42
  workers: 4

device: auto
